"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, ExternalLink, FileText, HelpCircle, Loader2, RefreshCcw, Shield, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { Button } from "@/components/ui/Button";
import type { CompanyReportBody, ReportSource } from "@/lib/research/report";

type Source = CompanyReportBody["moat"]["evidence"][number]["source"];

interface ReportResponse {
  lens: { key: string; name: string; questions: string[] };
  report: { id: string; report: CompanyReportBody; sources: { companyName: string; filings: ReportSource[]; lensName: string }; createdAt: string } | null;
  /** A running (or failed) background job newer than the report shown. */
  job: { id: string; status: "RUNNING" | "DONE" | "ERROR"; stages: string[]; error: string | null; startedAt: string } | null;
  available: Record<string, string>;
}

const POLL_MS = 2500;

const SECTION_NAMES: Record<string, string> = {
  business: "Business",
  riskFactors: "Risk Factors",
  mdna: "MD&A",
  marketRisk: "Market Risk",
  financials: "Financials",
  market_data: "Market data",
};

const MOAT_LABEL: Record<string, string> = {
  brand: "Brand",
  switching_costs: "Switching costs",
  network_effects: "Network effects",
  cost_advantage: "Cost advantage",
  efficient_scale: "Efficient scale",
  intangibles: "Intangibles",
};

const SEVERITY = { high: "bg-danger/12 text-danger", medium: "bg-warning/15 text-warning", low: "bg-border text-muted" } as const;
const TREND = { new: "New", rising: "Rising", stable: "Stable", fading: "Fading", unclear: "" } as const;
const FIT = {
  STRONG: "bg-success/12 text-success",
  PARTIAL: "bg-warning/15 text-warning",
  POOR: "bg-danger/12 text-danger",
} as const;
const MOAT_STYLE = { WIDE: "text-success", NARROW: "text-warning", NONE: "text-danger" } as const;

function Cite({ source, filings }: { source: Source; filings: ReportSource[] }) {
  if (!source) return <span className="text-[10px] text-muted/80 italic">inference</span>;
  const label = `${source.form}${source.fiscalYear ? ` FY${source.fiscalYear}` : ""} · ${SECTION_NAMES[source.section] ?? source.section}`;
  const filing = filings.find((f) => f.form === source.form && f.fiscalYear === source.fiscalYear);
  const cls = "inline-flex items-center gap-1 rounded-md bg-background border border-border px-1.5 py-0.5 text-[10px] text-muted whitespace-nowrap";
  return filing ? (
    <a href={filing.url} target="_blank" rel="noopener noreferrer" className={`${cls} hover:text-accent hover:border-accent/40`}>
      <FileText className="w-2.5 h-2.5" />
      {label}
    </a>
  ) : (
    <span className={cls}>{label}</span>
  );
}

function Section({ icon: Icon, title, children, aside }: { icon: typeof Shield; title: string; children: React.ReactNode; aside?: React.ReactNode }) {
  return (
    <section className="bg-card border border-border rounded-2xl shadow-card p-5 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <h3 className="flex items-center gap-2 text-sm font-semibold">
          <Icon className="w-4 h-4 text-accent" />
          {title}
        </h3>
        {aside}
      </div>
      {children}
    </section>
  );
}

function Points({ points, filings }: { points: { point: string; source: Source }[]; filings: ReportSource[] }) {
  return (
    <ul className="space-y-2">
      {points.map((p, i) => (
        <li key={i} className="text-sm leading-relaxed">
          {p.point} <Cite source={p.source} filings={filings} />
        </li>
      ))}
    </ul>
  );
}

/**
 * The AI Company Report for one stock under the page's selected lens. Mount with
 * `key={lens}` so switching lenses starts from a clean loading state.
 */
export function CompanyReport({
  accountId,
  symbol,
  lens,
  onReportReady,
}: {
  accountId: string;
  symbol: string;
  lens: string | null;
  /** Called when a newly generated report arrives (e.g. to refresh the score). */
  onReportReady?: () => void;
}) {
  const base = `/api/accounts/${accountId}/company/${encodeURIComponent(symbol)}/report`;
  const [data, setData] = useState<ReportResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [starting, setStarting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reports are generated by a server-side job, so leaving this tab doesn't stop
  // them: on return we pick the running job back up from the API and keep polling.
  const fetchReport = useCallback(async () => {
    const res = await fetch(`${base}?lens=${encodeURIComponent(lens ?? "none")}`);
    return res.ok ? ((await res.json()) as ReportResponse) : null;
  }, [base, lens]);

  useEffect(() => {
    let live = true;
    fetchReport().then((d) => {
      if (!live) return;
      setData(d);
      setLoading(false);
    });
    return () => {
      live = false;
    };
  }, [fetchReport]);

  const generating = data?.job?.status === "RUNNING";
  const jobError = data?.job?.status === "ERROR" ? data.job.error : null;
  const stages = data?.job?.stages ?? [];

  useEffect(() => {
    if (!generating) return;
    let live = true;
    const id = setInterval(() => {
      fetchReport().then((d) => live && d && setData(d));
    }, POLL_MS);
    return () => {
      live = false;
      clearInterval(id);
    };
  }, [generating, fetchReport]);

  const generate = async () => {
    setStarting(true);
    setError(null);
    try {
      const res = await fetch(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lens }) });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body.error ?? "Couldn't start the report");
      setData((d) => (d ? { ...d, job: body.job } : d));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Couldn't start the report");
    } finally {
      setStarting(false);
    }
  };

  // Tell the page when a new report replaces the one we first loaded.
  const firstReportId = useRef<string | null | undefined>(undefined);
  useEffect(() => {
    if (!data) return;
    const id = data.report?.id ?? null;
    if (firstReportId.current === undefined) firstReportId.current = id;
    else if (id !== firstReportId.current) {
      firstReportId.current = id;
      onReportReady?.();
    }
  }, [data, onReportReady]);

  const r = data?.report?.report;
  const filings = data?.report?.sources?.filings ?? [];
  const lensName = data?.lens.name ?? "";

  return (
    <div className="space-y-4">
      {data?.report && !generating && (
        <div className="flex justify-end">
          <div className="flex items-center gap-2 text-[11px] text-muted">
            Generated {new Date(data.report.createdAt).toLocaleDateString()}
            <Button size="sm" variant="ghost" onClick={generate} disabled={starting}>
              <RefreshCcw className="w-3.5 h-3.5" /> Regenerate
            </Button>
          </div>
        </div>
      )}

      {loading ? (
        <div className="flex justify-center py-16">
          <Loader2 className="w-6 h-6 animate-spin text-muted" />
        </div>
      ) : generating ? (
        <div className="bg-card border border-border rounded-2xl shadow-card p-6 space-y-3">
          <p className="flex items-center gap-2 text-sm font-semibold">
            <Sparkles className="w-4 h-4 text-accent" /> Writing the {lensName} report on {symbol}
          </p>
          <ul className="space-y-1.5">
            {stages.map((s, i) => (
              <li key={i} className="flex items-center gap-2 text-xs text-muted slide-in">
                {i === stages.length - 1 ? <Loader2 className="w-3 h-3 animate-spin text-accent" /> : <span className="w-3 h-3 grid place-items-center text-success">✓</span>}
                {s}
              </li>
            ))}
          </ul>
          <p className="text-[11px] text-muted">
            The first report on a company reads its last 5 annual reports and takes a couple of minutes. It keeps going in the
            background, so feel free to switch tabs or look at other stocks and come back.
          </p>
        </div>
      ) : !r ? (
        <div className="bg-card border border-border rounded-2xl shadow-card p-8 text-center space-y-3">
          <Sparkles className="w-6 h-6 mx-auto text-accent" />
          <h3 className="font-semibold">No {lensName} report on {symbol} yet</h3>
          <p className="text-sm text-muted max-w-lg mx-auto">
            The Analyst reads {symbol}&apos;s last 5 annual reports, 10 years of financials and live metrics, then answers:
          </p>
          <ul className="text-xs text-muted space-y-0.5 max-w-md mx-auto text-left list-disc pl-5">
            {data?.lens.questions.map((q) => <li key={q}>{q}</li>)}
          </ul>
          {(error || jobError) && <p className="text-xs text-danger">{error ?? `The last attempt failed: ${jobError}`}</p>}
          <Button onClick={generate} disabled={starting}>
            {starting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />} Generate {lensName} report
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          {(error || jobError) && (
            <p className="text-xs text-danger">{error ?? `Regenerating failed: ${jobError} The report below is the previous one.`}</p>
          )}
          <div className="rise-in bg-card border border-border rounded-2xl shadow-card p-5 space-y-3">
            <div className="flex flex-wrap items-center gap-2">
              <span className={`rounded-md px-2 py-0.5 text-xs font-semibold ${FIT[r.lensFit.verdict]}`}>
                {r.lensFit.verdict === "STRONG" ? "Strong fit" : r.lensFit.verdict === "PARTIAL" ? "Partial fit" : "Poor fit"} · {r.lensFit.score}/100
              </span>
              <span className="text-xs text-muted">{lensName} lens</span>
              <span className={`text-xs font-semibold ${MOAT_STYLE[r.moat.rating]}`}>· {r.moat.rating === "NONE" ? "No moat" : `${r.moat.rating === "WIDE" ? "Wide" : "Narrow"} moat`}</span>
            </div>
            <p className="text-base font-medium leading-snug">{r.oneLineVerdict}</p>
            <p className="text-sm text-muted leading-relaxed">{r.twoMinuteStory}</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <Section icon={TrendingUp} title="Competitive advantage">
              <p className="text-sm leading-relaxed">{r.competitiveAdvantage.summary}</p>
              <Points points={r.competitiveAdvantage.points} filings={filings} />
            </Section>

            <Section
              icon={Shield}
              title="Moat"
              aside={<span className={`text-xs font-semibold ${MOAT_STYLE[r.moat.rating]}`}>{r.moat.rating === "NONE" ? "None" : r.moat.rating === "WIDE" ? "Wide" : "Narrow"}</span>}
            >
              {r.moat.types.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {r.moat.types.map((t) => (
                    <span key={t} className="rounded-full bg-accent/10 text-accent px-2 py-0.5 text-[11px] font-medium">
                      {MOAT_LABEL[t] ?? t}
                    </span>
                  ))}
                </div>
              )}
              <p className="text-sm leading-relaxed">{r.moat.durability}</p>
              <Points points={r.moat.evidence} filings={filings} />
            </Section>
          </div>

          <Section icon={AlertTriangle} title="Greatest risks">
            <ol className="space-y-3">
              {r.greatestRisks.map((risk, i) => (
                <li key={i} className={`rounded-xl border p-3 ${i === 0 ? "border-danger/30 bg-danger/5" : "border-border"}`}>
                  <div className="flex flex-wrap items-center gap-2">
                    {i === 0 && <span className="text-[10px] uppercase tracking-[0.12em] font-semibold text-danger">Greatest risk</span>}
                    <span className={`rounded-md px-1.5 py-0.5 text-[10px] font-semibold ${SEVERITY[risk.severity]}`}>{risk.severity}</span>
                    {TREND[risk.trend] && <span className="text-[10px] text-muted">{TREND[risk.trend]}</span>}
                    <Cite source={risk.source} filings={filings} />
                  </div>
                  <p className="text-sm font-medium mt-1.5">{risk.risk}</p>
                  <p className="text-sm text-muted mt-0.5 leading-relaxed">{risk.whyItMatters}</p>
                </li>
              ))}
            </ol>
          </Section>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <Section icon={Users} title="Management & capital allocation">
              <p className="text-sm leading-relaxed">{r.management.assessment}</p>
              <p className="text-sm text-muted leading-relaxed">{r.management.capitalAllocation}</p>
              <Points points={r.management.points} filings={filings} />
            </Section>
            <Section icon={TrendingUp} title="Financial track record">
              <p className="text-sm leading-relaxed">{r.financialTrackRecord.summary}</p>
              <ul className="space-y-1 list-disc pl-5 text-sm text-muted">
                {r.financialTrackRecord.highlights.map((h, i) => (
                  <li key={i}>{h}</li>
                ))}
              </ul>
            </Section>
          </div>

          <Section icon={Target} title={`Through the ${lensName} lens`}>
            <p className="text-sm leading-relaxed">{r.lensFit.reasoning}</p>
            {r.lensFit.notes.length > 0 && (
              <dl className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {r.lensFit.notes.map((n, i) => (
                  <div key={i} className="rounded-xl bg-background border border-border p-3">
                    <dt className="text-[11px] uppercase tracking-[0.1em] font-semibold text-muted">{n.label}</dt>
                    <dd className="text-sm mt-1 leading-relaxed">{n.value}</dd>
                  </div>
                ))}
              </dl>
            )}
            {r.customAnswers.length > 0 && (
              <div className="space-y-2 pt-1">
                <p className="text-[11px] uppercase tracking-[0.1em] font-semibold text-muted">Your questions</p>
                {r.customAnswers.map((a, i) => (
                  <div key={i}>
                    <p className="text-sm font-medium">{a.question}</p>
                    <p className="text-sm text-muted leading-relaxed">{a.answer}</p>
                  </div>
                ))}
              </div>
            )}
          </Section>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <Section icon={RefreshCcw} title="What would change the picture">
              <ul className="space-y-1 list-disc pl-5 text-sm">
                {r.whatWouldChangeThePicture.map((x, i) => (
                  <li key={i}>{x}</li>
                ))}
              </ul>
            </Section>
            <Section icon={HelpCircle} title="Questions to investigate">
              <ul className="space-y-1 list-disc pl-5 text-sm">
                {r.questionsToInvestigate.map((x, i) => (
                  <li key={i}>{x}</li>
                ))}
              </ul>
            </Section>
          </div>

          <p className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted px-1">
            Sources:
            {filings.map((f) => (
              <a key={f.url} href={f.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 hover:text-accent">
                {f.form} FY{f.fiscalYear} <ExternalLink className="w-2.5 h-2.5" />
              </a>
            ))}
            · SEC XBRL financials · Yahoo market data. Lenses are inspired by publicly described investing approaches. Educational, not
            investment advice.
          </p>
        </div>
      )}
    </div>
  );
}
